// client/src/App.vue
<script setup lang="ts">
import Header from "./components/layout/Header.vue";
import CandidateTable from "./components/CandidateTable.vue";
</script>

<template>
  <Header title="Home" />
  <CandidateTable />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// client/src/App.tsx
import React from 'react';
import './App.css';
import Header from './components/layout/Header';
import CandidateTable from './components/CandidateTable';

function App() {
  return (
    <div className="App">
      <Header title={"Home"}/>
      <CandidateTable />
    </div>
  );
}

export default App;
